package:
  name: pyunitwizard
  version: 0.1

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python  {{ python }}
    - setuptools
    - numpy 

  run:
    - python  {{ python }}
    - numpy
    - pint

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides some useful methods and classes to...
  dev_url: https://github.com/uibcdf/PyUnitWizard
  doc_url: https://uibcdf.org/PyUnitWizard

